# Thanks to Tarek Ben Driss at https://gist.github.com/TarekBenDriss/3809a576c02dd0bf27ec835fc04abec4
name: Android CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11.0.10
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11.0.10
      - name: Unit tests
        run: bash ./gradlew test --stacktrace

  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11.0.10
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11.0.10
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk